name: Release Calculator

on:
  push:
    paths:
      - 'calculator/**'  # Trigger on pushes to calculator folder and subfolders

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify your desired Python version

      - name: Install dependencies
        run: pip install nuitka

      - name: Compile main.py for Windows
        run: |
          nuitka \
            --enable-plugin=tk-inter \
            --standalone \
            --disable-console \
            --windows-icon-from-ico=./calculator/main.ico \
            --output-dir=dist/windows \
            calculator/main.py

      - name: Create Release
        # Use the newer action for creating releases
        uses: actions/create-release@v1
        with:
         tag_name: 'v${{ github.sha }}'  # Generate a release tag based on commit SHA
         release_name: MC1323 Calculator
         draft: false
         prerelease: false
         body: |
           # Add release notes here

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/windows/*.exe
          asset_name: calculator.exe
          asset_content_type: application/vnd.microsoft.portable-executable
